[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/generate-sitemap"
  status = 200
