[build]
  functions = "netlify/functions"

[functions]
  included_files = ["assets/hero/**", "assets/testimoni/**"]

# --- TAMBAHKAN SELURUH BAGIAN INI ---
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' https://app.midtrans.com https://api.midtrans.com;"
# --- AKHIR BAGIAN TAMBAHAN ---

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/generate-sitemap"
  status = 200
